"""
Memory system, two tiers:

1. conversation_memories — a rolling summary *per conversation*. Once
   a conversation accumulates more than KEEP_RAW_MESSAGES un-summarized
   messages beyond the summarization trigger, the oldest chunk is
   collapsed into (or merged into) a single summary row generated by
   the model itself, and those messages are flagged `summarized`.
2. character_memories — durable, cross-conversation facts about the
   user or world state tied to a character (e.g. "user's dog is named
   Max"). These are small and always included, never summarized.

This keeps the prompt bounded regardless of how long a chat runs,
instead of truncating history outright.
"""
from core.database import db_cursor, now
import config


def get_conversation_summary(conversation_id):
    """Concatenate all stored summary chunks for a conversation into
    one block, oldest first."""
    with db_cursor() as cur:
        cur.execute(
            """SELECT summary FROM conversation_memories
               WHERE conversation_id = ? ORDER BY id ASC""",
            (conversation_id,),
        )
        rows = cur.fetchall()
    return "\n".join(r["summary"] for r in rows)


def get_character_memories(character_id):
    with db_cursor() as cur:
        cur.execute(
            "SELECT fact FROM character_memories WHERE character_id = ? ORDER BY id ASC",
            (character_id,),
        )
        rows = cur.fetchall()
    return [r["fact"] for r in rows]


def add_character_memory(character_id, fact):
    with db_cursor() as cur:
        cur.execute(
            "INSERT INTO character_memories (character_id, fact, created_at) VALUES (?, ?, ?)",
            (character_id, fact, now()),
        )
        return cur.lastrowid


def delete_character_memory(memory_id):
    with db_cursor() as cur:
        cur.execute("DELETE FROM character_memories WHERE id = ?", (memory_id,))


def _unsummarized_messages(cur, conversation_id):
    cur.execute(
        """SELECT * FROM messages
           WHERE conversation_id = ? AND summarized = 0 AND role != 'system'
           ORDER BY id ASC""",
        (conversation_id,),
    )
    return [dict(r) for r in cur.fetchall()]


def maybe_summarize(conversation_id):
    """Check whether this conversation has crossed the summarization
    threshold and, if so, roll the oldest excess messages into a new
    summary chunk. Cheap no-op otherwise. Call this after each
    assistant turn."""
    with db_cursor() as cur:
        pending = _unsummarized_messages(cur, conversation_id)

    if len(pending) <= config.SUMMARIZE_EVERY_N_MESSAGES:
        return False

    to_summarize = pending[: len(pending) - config.KEEP_RAW_MESSAGES]
    if not to_summarize:
        return False

    transcript = "\n".join(f"{m['role']}: {m['content']}" for m in to_summarize)
    existing = get_conversation_summary(conversation_id)

    from core.llm_engine import engine
    summary_prompt = [
        {
            "role": "system",
            "content": (
                "Summarize the following chat excerpt into a short, factual "
                "third-person memory (bullet points of key facts, decisions, "
                "and emotional beats only — no commentary). Merge it with the "
                "existing memory below rather than repeating it.\n\n"
                f"EXISTING MEMORY:\n{existing or '(none yet)'}"
            ),
        },
        {"role": "user", "content": transcript},
    ]
    new_summary = engine.generate(summary_prompt, stream=False, max_tokens=300, temperature=0.3)

    last_id = to_summarize[-1]["id"]
    with db_cursor() as cur:
        cur.execute(
            """INSERT INTO conversation_memories
               (conversation_id, summary, covers_up_to_message_id, created_at)
               VALUES (?, ?, ?, ?)""",
            (conversation_id, new_summary.strip(), last_id, now()),
        )
        cur.execute(
            f"""UPDATE messages SET summarized = 1
                WHERE conversation_id = ? AND id <= ?""",
            (conversation_id, last_id),
        )
    return True
